In [ ]:
print("Hello World")

import numpy as np
import matplotlib.pyplot as plt

def makeWeightArray(X,Xtran,y):
    prein = np.matmul(Xtran,X)
    postin = np.linalg.pinv(prein)
    prey = np.matmul(postin,Xtran)
    weight = np.matmul(prey,y)
    return weight

def getRows(matrix):
    return (matrix.shape[0])

def getColumns(matrix):
    return (matrix.shape[1])

def printWeight(weight):
    for i in range(0,getRows(weight),1):
        print("W"+str(i)+" = "+str(weight[i]))
        
def printRealEstateWeight(weight):
    print("Base Weight: "+str(weight[0]))
    print("Bedroom's Weight: "+str(weight[1]))
    print("Bathroom's Weight: "+str(weight[2]))
    print("Square Foot's Weight: "+str(weight[3]))
    print("Lot Square Foot's Weight: "+str(weight[4]))
    print("Year's Weight: "+str(weight[5]))
    

def examineRealEstateDelta(weight, X,output):
    rows = getRows(X)
    delta = np.zeros(rows)
    
    for i in range(0,rows,1):
        addition = 0;
        for j in range (0,6,1):
            addition =  addition + X[i][j]*weight[j]
            
        addition = abs(addition - output[i])
        delta[i] = addition
        
    return delta

def calculateTotalDelta(delta):
    total = 0;
    for i in range (0,getRows(delta),1):
        total = total +delta[i]
    return float(total)
    
def computePriceRealEstate(weight):
    print("Ok, How many bedroom's does the house have?")
    bed = float(input("Input number of bedrooms: "))
    print("How many Bathrooms?")
    bath = float(input("Input number of bathrooms: "))
    print("Give me the Sqft of the house.")
    sqft = float(input("The sqft of the house: "))
    print("How about the sqft of the lot?")
    sqftlot = float(input("Sqft of the lot: "))
    print("In which year was the house completed?: ")
    year = float(input("The year: "))
    
    final = weight[0] + weight[1]*bed + weight[2]*bath 
    
    final = final + weight[3]*sqft + weight[4]*sqftlot + weight[5]*year
    return final
    

In [14]:

print("Would you like to take in house data (1), or plug in your own stuff (2)")
question = int(input("1 or 2:"))

if (question == 2):
    print("How many features would you like?")
    features = int(input("Number of features: "))
    print("How many entries would you like?")
    entries = int(input("Number of entries: "))

    print("So you want a "+str(features)+" by "+str(entries)+" array?")


    X = np.ones((entries,features+1))
    print(X)
    output = np.zeros(entries)

    for i in range(0,entries,1):
        for j in range(0,features,1):
            entry = float(input("Input for entry "+str((i+1))+" feature "+str((j+1))+": "))
            X[i][j + 1] = entry
        output[i] = float(input("What is the output for entry "+str(i+1)+": "))
    print("X matrix:")
    print(X)

    print("X transpose:")
    Xtran = X.transpose()
    print(Xtran)
    """
    print("X Inverse:")
    Xinv = np.linalg.pinv(X)
    print(Xinv)

    print(np.matmul(X,Xinv))
    """
    weight = makeWeightArray(X,Xtran,output)
    print("")
    printWeight(weight)

elif (question == 1):
    print("Ok, give me the address!")
    features = 5
    f = open("C:\\Users\\jzbus\\data.dat", "r")
    entries = 0;
    for x in f:
        entries = entries + 1;
        
    print(str(entries)+" is the number of entries")
    X = np.ones((entries,features+1))
    print(X)
    output = np.zeros(entries)
    
    f = open("C:\\Users\\jzbus\\data.dat", "r")
    i = 0;
    for x in f:
        lin = x;
        datah = lin.split(" ")
        bed = float(datah[0])
        X[i][1] = bed
        X[i][2] = float(datah[1])
        X[i][3] = float(datah[2])
        X[i][4] = float(datah[3])
        X[i][5] =  float(datah[5])
        output[i] = float(datah[6])
        i= i +1;
        
    print(X)
    print(output)
    
    print("X transpose:")
    Xtran = X.transpose()
    print(Xtran)
    """
    print("X Inverse:")
    Xinv = np.linalg.pinv(X)
    print(Xinv)

    print(np.matmul(X,Xinv))
    """
    weight = makeWeightArray(X,Xtran,output)
    print("")
    printRealEstateWeight(weight)
    print ("This is the price you should sell it for: "+str(computePriceRealEstate(weight))+"$")
    delta = examineRealEstateDelta(weight,X,output)
    
    print(delta)
    eye = calculateTotalDelta(delta)
    print("Total delta: "+str(eye))
    
    print("Average Delta: "+str(eye/(getRows(delta))))
    
print("")



Would you like to take in house data (1), or plug in your own stuff (2)
1 or 2:1
Ok, give me the address!
35 is the number of entries
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1.00000e+00 2.00000e+00 1.00000e+00 6.40000e+02 1.08900e+04 1.96100e+03]
 [1.00000e+00 3.00000e+00 2.50000e+00 1.50300e+03 5.227

In [ ]:
def make1dx(X):
    printX = np.zeros(getRows(X))
    print(X)
    """
    for i in range(0,getColumns(X),1):
        print("this is i: "+str(i))
       # print(X[i][1])
        printX[i] = X[i][1]
        print(printX[i])
        return printX
      """
    print("this is the columns:"+str(getColumns(X)))
    print("this is the Rows:"+str(getRows(X)))
    for i in range(0,getRows(X),1):
        print("This is i: "+str(i))
        #print(X)
        
        printX[i] = X[i][1]
        print(printX[i])
        
    return printX

def makeFull2DArray(printX,y):
    
    full2d = np.zeros((entries,2))
    for i in range (0,entries,1):
        print("seagul")
    
    print(full2d)
    
    return full2d

if (features == 1):

    #print ("epic")
    plt.xlabel("x0")
    plt.ylabel("y")
    printX = make1dx(X)
    print(printX)
    
    makeFull2DArray(printX,output)
    for i in range(0,entries,1):
        print("H")
        plt.plot(printX[i],output[i],"ro")
    
    t = np.arange(np.amin(printX), np.amax(printX), 0.2)
    print("Weight1: "+str(weight[1]))
    print("Weight0: "+str(weight[0]))
    plt.plot(t,(weight[1])*t + weight[0],"b--")
    
    plt.show()
    
if (features == 2):
    ax = plt.axes(projection='3d')
    for i in range(0,entries,1):
        print("H")
        ax.plot(X[i][1],X[i][2],output[i],"ro")
        a = np.arange(0, 5., 0.2)
        b = np.arange(0, 5., 0.2)
        xline = np.linspace(0, 15, 1000)
        #ax.plot3d(a,b,((weight[2]*a) + (weight[1])*b + weight[0]),"b--")
